//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::favorites::Entity as Favorites;
pub use super::followers::Entity as Followers;
pub use super::users::Entity as Users;
