name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: realworld
          POSTGRES_USER: realworld
    steps:
      - uses: actions/checkout@v2
      - name: Install latest ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt
      - name: Run fmt
        run: make fmt

      - name: Run clippy
        run: make clippy

      - name: Run tests
        run: make test
